In [ ]:
1. Convert the given list into a numpy array and replace the odd elements with -2.
Lst =[[1,2,3],
      [4,5,6],
      [7,8,9]]


In [262]:
import numpy as np
Lst =[[1,2,3],
      [4,5,6],
      [7,8,9]]

x =np.array(Lst)

print(x)
x[x%2!=0]=-2
print("array after replacing odd elements with -2 \n",x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array after replacing odd elements with -2 
 [[-2  2 -2]
 [ 4 -2  6]
 [-2  8 -2]]


In [ ]:
2. In the numpy array given below print all the elements ranging from 8 to 15.
arr = [1,2,3,4,5,8,9,10,12,22,32,54,99,6,7]

In [263]:
import numpy as np
arr = [1,2,3,4,5,8,9,10,12,22,32,54,99,6,7]
arr[8:16]

[12, 22, 32, 54, 99, 6, 7]

In [ ]:
3. Create a 3*3 narray that includes numbers from 1 to 9 and swap columns 1 and 2.

In [264]:
arr = np.arange(1,10).reshape((3,3))
print(arr)
arr[:,[0,1]]=arr[:,[1,0]]
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 1 3]
 [5 4 6]
 [8 7 9]]


In [ ]:
4. In the given numpy array replace the NaN values with the average of columns
arr = np.array([[1.3, 2.5, 3.6, np.nan],
                [2.6, 3.3, np.nan, 5.5],
                [2.1, 3.2, 5.4, 6.5]])

In [265]:
arr = np.array([[1.3, 2.5, 3.6, np.nan],
                [2.6, 3.3, np.nan, 5.5],
                [2.1, 3.2, 5.4, 6.5]])

print(arr)
average = np.nanmean(arr,axis=0)

indices = np.where(np.isnan(arr))

for row,col in zip(*indices):
    arr[row,col]=average[col]
    
print(arr)

[[1.3 2.5 3.6 nan]
 [2.6 3.3 nan 5.5]
 [2.1 3.2 5.4 6.5]]
[[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


In [ ]:
5. For the numpy array given below perform the following operation:
i.Convert the numpy array into a numpy matrix
ii.Sort the values in a matrix
arr = [[2,4,6],
       [1,3,5]]

In [266]:
arr = [[2,4,6],
       [1,3,5]]
np_arr = np.array(arr)
print(np_arr)
np_mat = np.matrix(np_arr)
print(np_mat)

new_mat = np.hstack((np_mat[0,:],np_mat[1,:]))
new_mat.sort()
np_mat =new_mat.reshape((2,3))
print(np_mat)
print(type(np_mat))

[[2 4 6]
 [1 3 5]]
[[2 4 6]
 [1 3 5]]
[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [267]:
np.array([2,4,6],dtype=complex)

array([2.+0.j, 4.+0.j, 6.+0.j])

In [268]:
itemsize("Hello")

NameError: name 'itemsize' is not defined

In [ ]:
np_arr.itemsize()